# Generated by Django 5.1.4 on 2025-03-07 15:55

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('date', models.CharField(default='', max_length=100)),
                ('verificaton_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('newest', models.BooleanField(default=False)),
                ('promo', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('image', cloudinary.models.CloudinaryField(default='empty_q2cypk.png', max_length=255, verbose_name='Image')),
                ('image1', cloudinary.models.CloudinaryField(default='empty_q2cypk.png', max_length=255, verbose_name='Image1')),
                ('image2', cloudinary.models.CloudinaryField(default='empty_q2cypk.png', max_length=255, verbose_name='Image2')),
                ('image3', cloudinary.models.CloudinaryField(default='empty_q2cypk.png', max_length=255, verbose_name='Image3')),
                ('image4', cloudinary.models.CloudinaryField(default='empty_q2cypk.png', max_length=255, verbose_name='Image4')),
                ('productType', models.CharField(default='Pant', editable=False, max_length=20)),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=10)),
                ('product_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('review', models.CharField(max_length=150)),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sandal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('newest', models.BooleanField(default=False)),
                ('promo', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('image', cloudinary.models.CloudinaryField(default='empty_q2cypk.png', max_length=255, verbose_name='Image')),
                ('image1', cloudinary.models.CloudinaryField(default='empty_q2cypk.png', max_length=255, verbose_name='Image1')),
                ('image2', cloudinary.models.CloudinaryField(default='empty_q2cypk.png', max_length=255, verbose_name='Image2')),
                ('image3', cloudinary.models.CloudinaryField(default='empty_q2cypk.png', max_length=255, verbose_name='Image3')),
                ('image4', cloudinary.models.CloudinaryField(default='empty_q2cypk.png', max_length=255, verbose_name='Image4')),
                ('productType', models.CharField(default='Sandal', editable=False, max_length=20)),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('newest', models.BooleanField(default=False)),
                ('promo', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('image', cloudinary.models.CloudinaryField(default='empty_q2cypk.png', max_length=255, verbose_name='Image')),
                ('image1', cloudinary.models.CloudinaryField(default='empty_q2cypk.png', max_length=255, verbose_name='Image1')),
                ('image2', cloudinary.models.CloudinaryField(default='empty_q2cypk.png', max_length=255, verbose_name='Image2')),
                ('image3', cloudinary.models.CloudinaryField(default='empty_q2cypk.png', max_length=255, verbose_name='Image3')),
                ('image4', cloudinary.models.CloudinaryField(default='empty_q2cypk.png', max_length=255, verbose_name='Image4')),
                ('productType', models.CharField(default='Shirt', editable=False, max_length=20)),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('newest', models.BooleanField(default=False)),
                ('promo', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('image', cloudinary.models.CloudinaryField(default='empty_q2cypk.png', max_length=255, verbose_name='Image')),
                ('image1', cloudinary.models.CloudinaryField(default='empty_q2cypk.png', max_length=255, verbose_name='Image1')),
                ('image2', cloudinary.models.CloudinaryField(default='empty_q2cypk.png', max_length=255, verbose_name='Image2')),
                ('image3', cloudinary.models.CloudinaryField(default='empty_q2cypk.png', max_length=255, verbose_name='Image3')),
                ('image4', cloudinary.models.CloudinaryField(default='empty_q2cypk.png', max_length=255, verbose_name='Image4')),
                ('productType', models.CharField(default='Shoe', editable=False, max_length=20)),
                ('category', models.CharField(choices=[('Mocassin', 'Mocassin'), ('Basket', 'Basket'), ('Medical', 'Medical'), ('Classic', 'Classic')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PantDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.pant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductOrdered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField(editable=False)),
                ('product_type', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=50)),
                ('ref', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.client')),
            ],
        ),
        migrations.CreateModel(
            name='QuantityExceptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=20)),
                ('product_category', models.CharField(max_length=50)),
                ('product_ref', models.PositiveIntegerField()),
                ('product_name', models.CharField(max_length=50)),
                ('product_size', models.CharField(max_length=50)),
                ('delta_quantity', models.PositiveIntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.client')),
            ],
        ),
        migrations.CreateModel(
            name='SandalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.sandal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShirtDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.shirt')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShoeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.shoe')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
