# Generated by Django 5.1.4 on 2025-07-08 13:05

import cloudinary_storage.storage
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('newest', models.BooleanField(default=False)),
                ('promo', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('image', models.FileField(default='https://res.cloudinary.com/de2wpriie/image/upload/v1751978248/missing_image_gfidbm.jpg', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='documents/products')),
                ('image1', models.FileField(default='https://res.cloudinary.com/de2wpriie/image/upload/v1751978248/missing_image_gfidbm.jpg', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='documents/products')),
                ('image2', models.FileField(default='https://res.cloudinary.com/de2wpriie/image/upload/v1751978248/missing_image_gfidbm.jpg', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='documents/products')),
                ('image3', models.FileField(default='https://res.cloudinary.com/de2wpriie/image/upload/v1751978248/missing_image_gfidbm.jpg', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='documents/products')),
                ('image4', models.FileField(default='https://res.cloudinary.com/de2wpriie/image/upload/v1751978248/missing_image_gfidbm.jpg', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='documents/products')),
                ('productType', models.CharField(default='Pant', editable=False, max_length=20)),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=10)),
                ('product_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('review', models.CharField(max_length=150)),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sandal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('newest', models.BooleanField(default=False)),
                ('promo', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('image', models.FileField(default='https://res.cloudinary.com/de2wpriie/image/upload/v1751978248/missing_image_gfidbm.jpg', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='documents/products')),
                ('image1', models.FileField(default='https://res.cloudinary.com/de2wpriie/image/upload/v1751978248/missing_image_gfidbm.jpg', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='documents/products')),
                ('image2', models.FileField(default='https://res.cloudinary.com/de2wpriie/image/upload/v1751978248/missing_image_gfidbm.jpg', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='documents/products')),
                ('image3', models.FileField(default='https://res.cloudinary.com/de2wpriie/image/upload/v1751978248/missing_image_gfidbm.jpg', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='documents/products')),
                ('image4', models.FileField(default='https://res.cloudinary.com/de2wpriie/image/upload/v1751978248/missing_image_gfidbm.jpg', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='documents/products')),
                ('productType', models.CharField(default='Sandal', editable=False, max_length=20)),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('newest', models.BooleanField(default=False)),
                ('promo', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('image', models.FileField(default='https://res.cloudinary.com/de2wpriie/image/upload/v1751978248/missing_image_gfidbm.jpg', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='documents/products')),
                ('image1', models.FileField(default='https://res.cloudinary.com/de2wpriie/image/upload/v1751978248/missing_image_gfidbm.jpg', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='documents/products')),
                ('image2', models.FileField(default='https://res.cloudinary.com/de2wpriie/image/upload/v1751978248/missing_image_gfidbm.jpg', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='documents/products')),
                ('image3', models.FileField(default='https://res.cloudinary.com/de2wpriie/image/upload/v1751978248/missing_image_gfidbm.jpg', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='documents/products')),
                ('image4', models.FileField(default='https://res.cloudinary.com/de2wpriie/image/upload/v1751978248/missing_image_gfidbm.jpg', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='documents/products')),
                ('productType', models.CharField(default='Shirt', editable=False, max_length=20)),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('newest', models.BooleanField(default=False)),
                ('promo', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('image', models.FileField(default='https://res.cloudinary.com/de2wpriie/image/upload/v1751978248/missing_image_gfidbm.jpg', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='documents/products')),
                ('image1', models.FileField(default='https://res.cloudinary.com/de2wpriie/image/upload/v1751978248/missing_image_gfidbm.jpg', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='documents/products')),
                ('image2', models.FileField(default='https://res.cloudinary.com/de2wpriie/image/upload/v1751978248/missing_image_gfidbm.jpg', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='documents/products')),
                ('image3', models.FileField(default='https://res.cloudinary.com/de2wpriie/image/upload/v1751978248/missing_image_gfidbm.jpg', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='documents/products')),
                ('image4', models.FileField(default='https://res.cloudinary.com/de2wpriie/image/upload/v1751978248/missing_image_gfidbm.jpg', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='documents/products')),
                ('productType', models.CharField(default='Shoe', editable=False, max_length=20)),
                ('category', models.CharField(choices=[], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('date', models.CharField(default='', max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('exception', models.BooleanField(default=False)),
                ('waiting', models.BooleanField(default=True)),
                ('payment_mode', models.BooleanField(default=True, editable=False)),
                ('currency', models.CharField(default='MAD', max_length=100)),
                ('invoice', models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='documents/invoices')),
                ('delivery_form', models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='documents/delivery_forms')),
                ('delivered', models.BooleanField(default=False)),
                ('delivery_man', models.CharField(default=None, max_length=100, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.client')),
            ],
        ),
        migrations.CreateModel(
            name='PantDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.pant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductOrdered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField(editable=False)),
                ('product_type', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=50)),
                ('ref', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('available', models.BooleanField(default=True)),
                ('exception_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.client')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_products', to='store.order')),
            ],
        ),
        migrations.CreateModel(
            name='QuantityExceptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('product_type', models.CharField(max_length=20)),
                ('product_category', models.CharField(max_length=50)),
                ('product_ref', models.PositiveIntegerField()),
                ('product_name', models.CharField(max_length=50)),
                ('product_size', models.CharField(max_length=50)),
                ('delta_quantity', models.PositiveIntegerField()),
                ('treated', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.client')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order', to_field='order_id')),
            ],
        ),
        migrations.CreateModel(
            name='SandalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.sandal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShirtDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.shirt')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShoeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.shoe')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
