# Generated by Django 5.1.4 on 2026-03-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
