# Generated by Django 5.1.4 on 2025-05-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pant',
            name='category',
            field=models.CharField(choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='sandal',
            name='category',
            field=models.CharField(choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='category',
            field=models.CharField(choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='category',
            field=models.CharField(choices=[], max_length=100),
        ),
    ]
