# Generated by Django 5.1.4 on 2026-05-30 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_clientprofile_delete_loyalclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='last_name',
        ),
    ]
