# Generated by Django 5.1.4 on 2025-06-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_pant_category_alter_sandal_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='MAD', max_length=100),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='category',
            field=models.CharField(choices=[('ahmed', 'ahmed'), ('mostapha', 'mostapha'), ('Moccassin', 'Moccassin'), ('Basket', 'Basket'), ('Classic', 'Classic')], max_length=100),
        ),
    ]
