# Generated by Django 5.1.4 on 2026-05-30 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_clientprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_as_client', to='store.clientprofile'),
        ),
    ]
