# Generated by Django 5.1.4 on 2026-04-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productreview_delete_productreviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
