# Generated by Django 5.1.4 on 2025-06-07 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productordered',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_products', to='store.order'),
        ),
    ]
