# Generated by Django 5.1.4 on 2026-06-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_client_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='loyalty_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
