# Generated by Django 5.1.4 on 2026-06-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_clientprofile_city_clientprofile_loyalty_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
    ]
