# Generated by Django 5.1.4 on 2025-06-08 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_productordered_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='productordered',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
