# Generated by Django 5.1.4 on 2026-04-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_client_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.CharField(choices=[('not_paid', 'not_paid'), ('pending', 'pending'), ('paid', 'paid')], default='not_paid', max_length=50),
        ),
    ]
