# Generated by Django 5.1.4 on 2025-06-08 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_productordered_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productordered',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
