# Generated by Django 5.1.4 on 2026-06-12 20:35

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_category_producttype_remove_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(default='https://res.cloudinary.com/de2wpriie/image/upload/y9DpT_eouhy5.jpg', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='documents/products'),
        ),
    ]
