# Generated by Django 5.1.4 on 2025-06-08 19:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_productordered_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_form',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
