# Generated by Django 5.1.4 on 2025-06-08 21:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_delivery_form_order_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_form',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Delivery Form'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Invoice'),
        ),
    ]
