# Generated by Django 5.1.4 on 2026-06-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_newslettercampaign_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='loyalty_points',
            field=models.PositiveIntegerField(default=0, help_text='Points awarded to the client when this product is purchased'),
        ),
    ]
