# Generated by Django 5.1.4 on 2025-06-09 00:53

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_order_delivery_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_form',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='documents/'),
        ),
    ]
