# Generated by Django 5.1.4 on 2025-06-09 13:13

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_order_delivery_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_form',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='documents/delivery_forms'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='documents/invoices'),
        ),
    ]
