# Generated by Django 5.1.4 on 2025-06-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_order_delivery_form_alter_order_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='productordered',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pant',
            name='ref',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sandal',
            name='ref',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='ref',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='category',
            field=models.CharField(choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='ref',
            field=models.CharField(max_length=100),
        ),
    ]
