# Generated by Django 5.1.4 on 2025-06-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_productordered_available_alter_pant_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productordered',
            name='exception_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='quantityexceptions',
            name='treated',
            field=models.BooleanField(default=False),
        ),
    ]
