# Generated by Django 5.1.4 on 2025-06-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_productordered_exception_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productordered',
            name='exception_id',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
