# Generated by Django 5.1.4 on 2025-06-26 10:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_productordered_exception_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantityexceptions',
            name='exception_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='productordered',
            name='exception_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
