# Generated by Django 5.1.4 on 2026-05-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('delivery', 'Delivery'), ('client', 'Client')], default='client', max_length=20),
        ),
    ]
