# Generated by Django 5.1.4 on 2025-10-03 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='authuser',
            managers=[
            ],
        ),
    ]
